bmFtZTogQ0kvQ0QgUGlwZWxpbmUKCm9uOgogIHB1c2g6CiAgICBicmFuY2hl
czogWyBtYWluIF0KICBwdWxsX3JlcXVlc3Q6CiAgICBicmFuY2hlczogWyBt
YWluIF0KICB3b3JrZmxvd19kaXNwYXRjaDoKICAgIGlucHV0czoKICAgICAg
ZmVhdHVyZUtleTogCiAgICAgICAgZGVzY3JpcHRpb246ICdUaGUgZmVhdHVy
ZSBrZXkgdG8gcnVuIENJIGZvciAoZS5nLiwgRkVBVC0xMjMpJwogICAgICAg
IHJlcXVpcmVkOiB0cnVlCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgIGF0
dGVtcHQ6IAogICAgICAgIGRlc2NyaXB0aW9uOiAnVGhlIGF0dGVtcHQgbnVt
YmVyIGZvciB0aGlzIENJIHJ1bicKICAgICAgICByZXF1aXJlZDogdHJ1ZQog
ICAgICAgIHR5cGU6IHN0cmluZwoKZW52OgogIERPVE5FVF9WRVJTSU9OOiAn
OC4wLngnCiAgTk9ERV9WRVJTSU9OOiAnMTgueCcKICBCQUNLRU5EX0RJUjog
J2NvZGUvYmFja2VuZCcKICBGUk9OVEVORF9ESVI6ICdjb2RlJyAgIyBhZGp1
c3RlZCBiZWNhdXNlIHRoZXJlIGlzIG5vIGNvZGUvZnJvbnRlbmQgZGlyZWN0
b3J5Cgpqb2JzOgogIGJ1aWxkLXRlc3Q6CiAgICBydW5zLW9uOiB1YnVudHUt
bGF0ZXN0CgogICAgc3RlcHM6CiAgICAtIHVzZXM6IGFjdGlvbnMvY2hlY2tv
dXRAdjQKCiAgICAtIG5hbWU6IFNldCB1cCAuTkVUCiAgICAgIHVzZXM6IGFj
dGlvbnMvc2V0dXAtZG90bmV0QHY0CiAgICAgIHdpdGg6CiAgICAgICAgZG90
bmV0LXZlcnNpb246ICR7eyBlbnYuRE9UTkVUX1ZFUlNJT04gfX0KCiAgICAt
IG5hbWU6IFJlc3RvcmUgYmFja2VuZCBkZXBlbmRlbmNpZXMKICAgICAgcnVu
OiB8CiAgICAgICAgY2QgJHt7IGVudi5CQUNLRU5EX0RJUiB9fQogICAgICAg
IGRvdG5ldCByZXN0b3JlIC4vQ1ZTeXN0ZW0uc2xuCgogICAgLSBuYW1lOiBC
dWlsZCBiYWNrZW5kCiAgICAgIHJ1bjogfAogICAgICAgIGNkICR7eyBlbnYu
QkFDS0VORF9ESVIgfX0KICAgICAgICBkb3RuZXQgYnVpbGQgLi9DVlN5c3Rl
bS5zbG4gLS1uby1yZXN0b3JlCgogICAgLSBuYW1lOiBUZXN0IGJhY2tlbmQK
ICAgICAgcnVuOiB8CiAgICAgICAgY2QgJHt7IGVudi5CQUNLRU5EX0RJUiB9
fQogICAgICAgIGRvdG5ldCB0ZXN0IC4vQ1ZTeXN0ZW0uc2xuIC0tbm8tYnVp
bGQgLS12ZXJib3NpdHkgbm9ybWFsIHx8IGVjaG8gIk5vIGJhY2tlbmQgdGVz
dHMgZm91bmQsIHNraXBwaW5nLiIKCiAgICAtIG5hbWU6IFNldCB1cCBOb2Rl
LmpzCiAgICAgIHVzZXM6IGFjdGlvbnMvc2V0dXAtbm9kZUB2NAogICAgICB3
aXRoOgogICAgICAgIG5vZGUtdmVyc2lvbjogJHt7IGVudi5OT0RFX1ZFUlNJ
T04gfX0KCiAgICAtIG5hbWU6IEluc3RhbGwgZnJvbnRlbmQgZGVwZW5kZW5j
aWVzCiAgICAgIHJ1bjogfAogICAgICAgIGNkICR7eyBlbnYuRlJPTlRFTkRf
RElSIH19CiAgICAgICAgbnBtIGNpIHx8IGVjaG8gIk5vIGZyb250ZW5kIHBy
b2plY3QgZm91bmQsIHNraXBwaW5nIG5wbSBjaS4iCgogICAgLSBuYW1lOiBC
dWlsZCBmcm9udGVuZAogICAgICBydW46IHwKICAgICAgICBjZCAke3sgZW52
LkZST05URU5EX0RJUiB9fQogICAgICAgIG5wbSBydW4gYnVpbGQgfHwgZWNo
byAiTm8gZnJvbnRlbmQgYnVpbGQgc2NyaXB0IGZvdW5kLCBza2lwcGluZyBi
dWlsZC4iCgogICAgLSBuYW1lOiBVcGRhdGUgcHJvZ3Jlc3MgcmVwb3J0CiAg
ICAgIHJ1bjogfAogICAgICAgIEZFQVRVUkVfS0VZPSIke3sgZ2l0aHViLmV2
ZW50LmlucHV0cy5mZWF0dXJlS2V5IH19IgogICAgICAgIEFUVEVNUFQ9IiR7
eyBnaXRodWIuZXZlbnQuaW5wdXRzLmF0dGVtcHQgfX0iCiAgICAgICAgUkVQ
T1JUX0ZJTEU9InBzZWMta2l0LWZpbGUvJHtGRUFUVVJFX0tFWX0vUFJPR1JF
U1NfUkVQT1JULm1kIgoKICAgICAgICBpZiBbIC1mICIkUkVQT1JUX0ZJTEUi
IF07IHRoZW4KICAgICAgICAgIGVjaG8gIkNJIFJ1biBmb3IgRmVhdHVyZSAk
RkVBVFVSRV9LRVksIEF0dGVtcHQgJEFUVEVNUFQ6IFNVQ0NFU1Mgb3IgY29t
cGxldGVkIHdpdGggd2FybmluZ3MiID4+ICIkUkVQT1JUX0ZJTEUiCiAgICAg
ICAgZWxzZQogICAgICAgICAgZWNobyAiUHJvZ3Jlc3MgcmVwb3J0IGZpbGUg
bm90IGZvdW5kIGF0ICRSRVBPUlRfRklMRS4gU2tpcHBpbmcgdXBkYXRlLiIg
CiAgICAgICAgZmkKICAgICAgc2hlbGw6IGJhc2gK
